### ISSUE TITLE
JSON to CSV challenge

### ISSUE THREAD

**Issue by xtradev** [BartJongejan/Bracmat#1]
Hi,

I was interested to employ Bracmat to solve [this JSON to CSV challenge](http://gist.github.com/jorin-vogel/2e43ffa981a97bc17259).

While I was able to produce the desired result, I was not able to make it fast (the processing time is noticeable). I wonder if I defined the pattern so that it does excessive backtracking:

`get$("data.json",JSN) : (, ? (?+(creditcard..?card)+?+(name..?name)+? & out$str$("\"" !name "\", " !card) & ~) ?)`

Could you, please, look at this and improve it?

**Comment by BartJongejan** [comment]
First thing: the line as shown above does not produce results, because a comma is missing in the pattern. The line below is a corrected version:

```
get$("data.json",JSN) : (, ? ((?+(creditcard..?card)+?+(name..?name)+?,) & out$str$("\"" !name "\", " !card) & ~) ?)
```

The pattern does not do excessive backtracking. Yet, at the cost of brevity and elegance, the expression can be made faster. 

1) If you run the expression in Bracmat's interactive mode (i.e. you start Bracmat and past in the expression after the {?} prompt), a lot of time is spent with printing the 5004 lines to screen. At least, in Windows that is slow. I would write results to a file on disk. Even appending 5004 times to an existing file can be faster than printing to screen. On Windows, that is.

2) Traversing data the way you do is by far the most effective way if the data is a huge string, but if the data is a long list it can be more efficient to just loop through it, especially if there are many hits in the list. I got a noticeable improvement by using a while loop instead of forced backtracking.

3) Concatenating 25000 strings in one operation is faster than concatenating five strings 5000 times. In my solution i prepend (much cheaper than appending!) all output elements in reversed order to a list. When all input data is parsed, the list is reversed in a while loop and then concatenated and written to a file.

With these improvements the creation of a csv file took under one second. Here is the code:

```
get$("data.json",JSN):(,?jsn)&:?L:?M&whl'(!jsn:? (?+(creditcard..?card)+?+(name..?name)+?,) ?jsn&\n !card "\", " !name \" !L:?L)&whl'(!L:%?s ?L&!s !M:?M)&put$(str$!M,"output.csv",NEW);
```

Or, in indented form

```
  get$("data.json",JSN):(,?jsn)
& :?L:?M
&   whl
  ' (   !jsn
      :   ?
          (?+(creditcard..?card)+?+(name..?name)+?,)
          ?jsn
    & \n !card "\", " !name \" !L:?L
    )
& whl'(!L:%?s ?L&!s !M:?M)
& put$(str$!M,"output.csv",NEW)
```

**Comment by xtradev** [comment]
Thank you Bart. These clarifications are helpful.

I was not sure why you are saying it does not produce results until I checked the Bracmat version that I have. I have version 6, build 169 (4 December 2013) installed on Windows XP SP3.
That most likely the reason. I should compile the most recent one.

Interesting enough, your corrected version does not produce results on my system and mine does.
I came up with it through trial and error so I am sure :)

I ran it via batch file:

```
SET file=%@substr[%_datetime,0,8].csv
ECHO name,card > %file & bracmat get$\"json2csv.bra\" >> %file
```

Changing
`(?+(creditcard..?card)+?+(name..?name)+?,)`
back to
`?+(creditcard..?card)+?+(name..?name)+?`
in your final version, again allows it to run on my system but takes long to finish.
That should not be discussed of course until I install the latest version.

Thank you.
