### ISSUE TITLE
rev function replaces accented characters by question marks.

### ISSUE THREAD

**Issue by Pytheas01** [BartJongejan/Bracmat#9]
{?} map$(rev.éléphant)
{!} tnahp??l??
    S   0,00 sec  (3920.3948)

OS : Macos 11.3.1
Bracmat version : 6.7.4

I've typed the acute accents with both the American keyboard (option-e = é) and the US PC international keyboard ('-e = é), on my Mac. The issue is the same in both cases.

**Comment by BartJongejan** [comment]
The reason is that the rev function reverses the byte order in the input string, not the character order. So if the string to be reversed contains UTF-8 characters consisting of two or more bytes, then the result is not valid UTF-8. But it is still a result. You can see that by reversing the result, which will return the original word:

{?} map$(rev.map$(rev.élélphant))
{!} élélphant

So when you see question marks it is because your terminal protests against having to display a non-UTF-8 string.

**Comment by Pytheas01** [comment]
Hi Bart,
you're absolutely right. Both Perl 5 and Python 3 behave the same as Bracmat in this particular instance. Case closed.
